### PR TITLE
Avoid a warning on Erlang/OTP 24

### LINKED ISSUE #145: Warnings emitted on OTP 24 prevent Rebar 3 bootstrap
This project is a dependency of Rebar 3. It has recently started failing bootstrap on Erlang/OTP 24 (master) due to the following warning:

```
/path/to/rebar3-src/_build/default/lib/erlware_commons/src/ec_cmd_log.erl:160: Warning: ambiguous call of overridden auto-imported BIF error/3
 - use erlang:error/3 or "-compile({no_auto_import,[error/3]})." to resolve name clash
```

Most likely this warning is relatively new but I did not spend any time trying to trace it to a specific OTP commit.

### PR DESCRIPTION
**Pull request by michaelklishin**
to make sure Rebar 3 can bootstrap on that version with warnings-as-errors compiler settings.

Closes #145.

### CODE REVIEW

File: src/ec_cmd_log.erl [hunk 1]
```diff
@@ -22,6 +22,9 @@
 %%% use this to talk to the users if you are wrting code for the system
 -module(ec_cmd_log).
 
+%% Avoids a warning on Erlang/OTP 24
```
Comment (ferd) [inline src/ec_cmd_log.erl:25]:
```suggestion
%% Avoid clashing with `error/3` BIF added in Erlang/OTP 24
```

**Comment by michaelklishin** [comment]
@ferd thank you for the wording suggestion, this is ready for another round.

**Review by tsloughter — APPROVED** [review]
